version: '3'
services:
  tadarr:
    container_name: tadarr
    image: athulp/tadarr
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./config.yaml:/app/config.yaml:ro
    - /home/pi/downloads:/downloads
