version: '3'
services:
  tadarr:
    container_name: tadarr
    image: ghcr.io/athulp01/tadarr:master
    restart: unless-stopped
    network_mode: host
    volumes:
    - ./config.yaml:/app/config.yaml:ro
    - /home/pi/downloads:/downloads
